#############################################################################
# Makefile for building: SymbianSimplePlayer
# Generated by qmake (2.01a) (Qt 4.6.0) on: Fri Dec 18 18:46:41 2009
# Project:  SymbianSimplePlayer.pro
# Template: app
# Command: /home/f3ex/qtsdk-2009.05/qt/bin/qmake -spec ../../qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SymbianSimplePlayer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2009.05/qt/mkspecs/linux-g++ -I. -I../../qtsdk-2009.05/qt/include/QtCore -I../../qtsdk-2009.05/qt/include/QtGui -I../../qtsdk-2009.05/qt/include/QtXml -I../../qtsdk-2009.05/qt/include/QtSql -I../../qtsdk-2009.05/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/f3ex/qtsdk-2009.05/qt/lib
LIBS          = $(SUBLIBS)  -L/home/f3ex/qtsdk-2009.05/qt/lib -lQtSql -L/home/f3ex/qtsdk-2009.05/qt/lib -lQtXml -lQtGui -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/f3ex/qtsdk-2009.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		player.cpp moc_player.cpp
OBJECTS       = main.o \
		player.o \
		moc_player.o
DIST          = ../../qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		SymbianSimplePlayer.pro
QMAKE_TARGET  = SymbianSimplePlayer
DESTDIR       = 
TARGET        = SymbianSimplePlayer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_player.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SymbianSimplePlayer.pro  ../../qtsdk-2009.05/qt/mkspecs/linux-g++/qmake.conf ../../qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		/home/f3ex/qtsdk-2009.05/qt/lib/libQtSql.prl \
		/home/f3ex/qtsdk-2009.05/qt/lib/libQtCore.prl \
		/home/f3ex/qtsdk-2009.05/qt/lib/libQtXml.prl \
		/home/f3ex/qtsdk-2009.05/qt/lib/libQtGui.prl
	$(QMAKE) -spec ../../qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SymbianSimplePlayer.pro
../../qtsdk-2009.05/qt/mkspecs/common/g++.conf:
../../qtsdk-2009.05/qt/mkspecs/common/unix.conf:
../../qtsdk-2009.05/qt/mkspecs/common/linux.conf:
../../qtsdk-2009.05/qt/mkspecs/qconfig.pri:
../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2009.05/qt/mkspecs/features/debug.prf:
../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf:
../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2009.05/qt/mkspecs/features/qt.prf:
../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2009.05/qt/mkspecs/features/moc.prf:
../../qtsdk-2009.05/qt/mkspecs/features/resources.prf:
../../qtsdk-2009.05/qt/mkspecs/features/uic.prf:
../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf:
../../qtsdk-2009.05/qt/mkspecs/features/lex.prf:
../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf:
/home/f3ex/qtsdk-2009.05/qt/lib/libQtSql.prl:
/home/f3ex/qtsdk-2009.05/qt/lib/libQtCore.prl:
/home/f3ex/qtsdk-2009.05/qt/lib/libQtXml.prl:
/home/f3ex/qtsdk-2009.05/qt/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SymbianSimplePlayer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SymbianSimplePlayer1.0.0 || $(MKDIR) .tmp/SymbianSimplePlayer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SymbianSimplePlayer1.0.0/ && $(COPY_FILE) --parents player.h .tmp/SymbianSimplePlayer1.0.0/ && $(COPY_FILE) --parents main.cpp player.cpp .tmp/SymbianSimplePlayer1.0.0/ && $(COPY_FILE) --parents player.ui .tmp/SymbianSimplePlayer1.0.0/ && (cd `dirname .tmp/SymbianSimplePlayer1.0.0` && $(TAR) SymbianSimplePlayer1.0.0.tar SymbianSimplePlayer1.0.0 && $(COMPRESS) SymbianSimplePlayer1.0.0.tar) && $(MOVE) `dirname .tmp/SymbianSimplePlayer1.0.0`/SymbianSimplePlayer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SymbianSimplePlayer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_player.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_player.cpp
moc_player.cpp: player.h
	/home/f3ex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) player.h -o moc_player.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_player.h
compiler_uic_clean:
	-$(DEL_FILE) ui_player.h
ui_player.h: player.ui
	/home/f3ex/qtsdk-2009.05/qt/bin/uic player.ui -o ui_player.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

player.o: player.cpp player.h \
		ui_player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

